name: 'OpenActive Test Suite'
description: 'Test suite for OpenActive implementations'
inputs:
  args:  # id of input
    description: 'Arguments to pass to `npm start` of OpenActive Test Suite'
    required: false
    default: ''
  NODE_CONFIG:  # id of input
    description: 'JSON configuration string to pass into OpenActive Test Suite'
    required: true
    default: '{ "ci": true }'
  NODE_ENV:  # id of input
    description: 'Value of NODE_ENV environment variable to pass into OpenActive Test Suite'
    required: false
    default: ''
  NODE_APP_INSTANCE:  # id of input
    description: 'Value of NODE_APP_INSTANCE environment variable to pass into OpenActive Test Suite'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/openactive/test-suite:feature-docker'
  args:
    - ${{ inputs.args }}
  env:
    FORCE_COLOR: 1
    NODE_CONFIG: ${{ inputs.NODE_CONFIG }}
    NODE_ENV: ${{ inputs.NODE_ENV }}
    NODE_APP_INSTANCE: ${{ inputs.NODE_APP_INSTANCE }}
    