name: Code Tests

on:
  # This does not run on push to master, as tests will instead be run there as
  # part of the docker.yml workflow.
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenActive Test Suite
      uses: actions/checkout@v4
    - name: Setup Node.js 18.17.1
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
    - name: Install OpenActive Test Suite
      run: npm install
    - name: Run Checks on the Code (Test the Tests!)
      run: npm test
