name: Code Tests

on:
  push:
    branches: [ feature/docker-and-package-upgrades ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenActive Test Suite
      uses: actions/checkout@v2
    - name: Setup Node.js 18.17.1
      uses: actions/setup-node@v1
      with:
        node-version: 18.17.1
    - name: Install OpenActive Test Suite
      run: npm install
    - name: Check licenses of all dependencies are at least permissive
      run: npx npm-consider install --test
    - name: Run Checks on the Code (Test the Tests!)
      run: npm test
