name: Code Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenActive Test Suite
      uses: actions/checkout@v4
    - name: Setup Node.js 18.17.1
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.1
    - name: Install OpenActive Test Suite
      run: npm install
    - name: Check licenses of all dependencies are at least permissive
      run: |
        npx npm-reflect install --test
        for dir in ./packages/*; do (cd "$dir" && npx npm-reflect install --test); done
    - name: Run Checks on the Code (Test the Tests!)
      run: npm test
